<?php

namespace AppBundle\Repository\Crowding;

/**
 * TranslationToLangRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TranslationToLangRepository extends \Doctrine\ORM\EntityRepository
{
}
