<?php

namespace AppBundle\Repository\Crowding;

/**
 * TranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
